services:
  san-maldito:
    networks:
      - san-maldito
      - sginfra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.san-maldito.rule=Host(`${SAN_MALDITO_HOST}`)"
      - "traefik.http.routers.san-maldito.entrypoints=websecure"
      - "traefik.http.routers.san-maldito.tls=true"
      - "traefik.http.services.san-maldito.loadbalancer.server.port=3000"

networks:
  sginfra:
    external: true
    name: "${SGINFRA_NETWORK:-sginfra}"
